(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const d of e.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function s(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function a(t){if(t.ep)return;t.ep=!0;const e=s(t);fetch(t.href,e)}})();const y=async(o,r=1,s=40)=>{const t=`https://pixabay.com/api/?key=48615456-7478b61ba219341e00e1cbdfc&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${s}`;console.log(t);try{const e=await axios.get(t);if(console.log(`Total images found: ${e.data.totalHits}`),!e.data.hits||e.data.hits.length===0)throw console.log(`No images found for query: ${o}`),new Error("No images found for the given search query.");return console.log(`Found ${e.data.totalHits} images.`),{images:e.data.hits,totalHits:e.data.totalHits}}catch(e){throw console.error("Error fetching images:",e),new Error(e.message)}},m=o=>{const r=document.querySelector(".gallery"),s=o.map(e=>`
    <a href="${e.largeImageURL}">
      <div class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </div>
    </a>
    `).join("");r.insertAdjacentHTML("beforeend",s),new SimpleLightbox(".gallery a");const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:2*t,behavior:"smooth"})},p=()=>{iziToast.error({title:"Sorry",message:"There are no images matching your search query. Please try again!"})},l=()=>{const o=document.querySelector(".loader");o.style.display="none"},u=()=>{iziToast.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",timeout:5e3})},w=document.querySelector("#search-form"),b=document.querySelector(".search-input"),h=document.querySelector(".loader"),f=document.querySelector(".gallery"),n=document.querySelector("#load-more");let c=1,i="",g=0;console.log(iziToast);w.addEventListener("submit",async o=>{if(o.preventDefault(),console.log("Search button clicked"),i=b.value.trim(),i!==""){c=1,h.style.display="block",n.style.display="none",f.innerHTML="";try{const{images:r,totalHits:s}=await y(i,c);l(),g=s,r.length>0?(m(r),r.length<g?n.style.display="block":u()):p()}catch{l(),iziToast.error({title:"Sorry",message:"An error occurred while fetching the images."})}}});n.addEventListener("click",async()=>{c+=1,h.style.display="block";try{const{images:o}=await y(i,c);l(),o.length>0?(m(o),f.children.length>=g&&(n.style.display="none",u())):(n.style.display="none",u())}catch{l(),iziToast.error({title:"Sorry",message:"An error occurred while fetching the images."})}});
//# sourceMappingURL=index.js.map
