(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const d of t.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const y=async(o,r=1,s=15)=>{const e=`https://pixabay.com/api/?key=48615456-7478b61ba219341e00e1cbdfc&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${s}`;console.log(e);try{const t=await axios.get(e);if(console.log(`Total images found: ${t.data.totalHits}`),!t.data.hits||t.data.hits.length===0)throw console.log(`No images found for query: ${o}`),new Error("No images found for the given search query.");return console.log(`Found ${t.data.totalHits} images.`),{images:t.data.hits,totalHits:t.data.totalHits}}catch(t){throw console.error("Error fetching images:",t),new Error(t.message)}};let p=new SimpleLightbox(".gallery a");const m=o=>{const r=document.querySelector(".gallery"),s=o.map(e=>`
    <a href="${e.largeImageURL}">
      <div class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </div>
    </a>
    `).join("");r.insertAdjacentHTML("beforeend",s),p.refresh(),document.querySelector(".gallery-item").getBoundingClientRect().height},w=()=>{iziToast.error({title:"Sorry",message:"There are no images matching your search query. Please try again!"})},h=o=>{const r=document.querySelector(".loader");(o==="search"||o==="loadMore")&&(r.style.display="block")},i=()=>{const o=document.querySelector(".loader");o.style.display="none"},u=()=>{iziToast.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",timeout:5e3})},b=document.querySelector("#search-form"),L=document.querySelector(".search-input");document.querySelector(".loader");const f=document.querySelector(".gallery"),l=document.querySelector("#load-more");let c=1,a="",g=0;console.log(iziToast);b.addEventListener("submit",async o=>{if(o.preventDefault(),console.log("Search button clicked"),a=L.value.trim(),a!==""){c=1,h("search"),l.style.display="none",f.innerHTML="";try{const{images:r,totalHits:s}=await y(a,c);i(),g=s,r.length>0?(m(r),r.length<g?l.style.display="block":u()):w()}catch{i(),iziToast.error({title:"Sorry",message:"An error occurred while fetching the images."})}}});l.addEventListener("click",async()=>{c+=1,h("loadMore"),setTimeout(()=>{},5500);try{const{images:o}=await y(a,c);i(),o.length>0?(m(o),f.children.length>=g&&(l.style.display="none",u()),S()):(l.style.display="none",u())}catch{i(),iziToast.error({title:"Sorry",message:"An error occurred while fetching the images."})}});const S=()=>{const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:2*r,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
